//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchase_id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReferenceNo { get; set; }
        public string Supplier { get; set; }
        public string PurchaseStatus { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PaymentStatus { get; set; }
    }
}
