//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.DateTime Date { get; set; }
        public string ReferenceNo { get; set; }
        public string Biller { get; set; }
        public string Customer { get; set; }
        public decimal Tax { get; set; }
        public decimal OrderDiscount { get; set; }
        public decimal Shipping { get; set; }
        public string Paid { get; set; }
        public string Status { get; set; }
        public int SaleID { get; set; }
    }
}
